services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echofy_chatbot
    ports: 
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma:/app/chroma
    networks:
      - echofy-net

networks:
  echofy-net:
    external: true
    name: echofy-shared-network