services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echofy_chatbot
    ports: 
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HF_HUB_DOWNLOAD_TIMEOUT=60
    volumes:
      - ./chroma:/app/chroma
      - hf_cache:/root/.cache/huggingface
    networks:
      - echofy-net

volumes:
  hf_cache:

networks:
  echofy-net:
    external: true
    name: echofy-shared-network